# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/torchserve_client',
                'doc_host': 'https://Ankur-singh.github.io',
                'git_url': 'https://github.com/Ankur-singh/torchserve_client',
                'lib_path': 'torchserve_client'},
  'syms': {'torchserve_client.core': {'torchserve_client.core.foo': ('core.html#foo', 'torchserve_client/core.py')}}}
