project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: "docked"
    contents:
      - index.ipynb
      - 01_rest.ipynb
      - 02_grpc.ipynb

metadata-files: [nbdev.yml]